/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/meta/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sources */
        get: operations["sources_meta_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Batches */
        get: operations["batches_meta_batches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quality */
        get: operations["quality_meta_quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/quality/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quality Runs */
        get: operations["quality_runs_meta_quality_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Layers
         * @description Số dòng từng bảng ở mỗi tầng, theo lần profile mới nhất (quality.runner ghi).
         */
        get: operations["layers_meta_layers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tables */
        get: operations["tables_catalog_tables_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/tables/{name}/columns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Columns
         * @description `name` dạng `schema.table`, ví dụ `core.fct_main`.
         */
        get: operations["columns_catalog_tables__name__columns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Batch */
        Batch: {
            /**
             * Batch Id
             * Format: uuid
             */
            batch_id: string;
            /** Source Name */
            source_name: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Status */
            status: string;
            /** Rows Fetched */
            rows_fetched: number | null;
            /** Row Count */
            row_count: number | null;
            /** Bytes */
            bytes: number | null;
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Error Message */
            error_message: string | null;
        };
        /** Column */
        Column: {
            /** Position */
            position: number;
            /** Column Name */
            column_name: string;
            /** Data Type */
            data_type: string;
            /** Nullable */
            nullable: boolean;
            /** Comment */
            comment: string | null;
            /** Null Count */
            null_count: number | null;
            /** Null Rate */
            null_rate: string | null;
        };
        /** Envelope[list[Batch]] */
        Envelope_list_Batch__: {
            /** Data */
            data: components["schemas"]["Batch"][];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[list[Column]] */
        Envelope_list_Column__: {
            /** Data */
            data: components["schemas"]["Column"][];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[list[LayerTable]] */
        Envelope_list_LayerTable__: {
            /** Data */
            data: components["schemas"]["LayerTable"][];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[list[QualityCheck]] */
        Envelope_list_QualityCheck__: {
            /** Data */
            data: components["schemas"]["QualityCheck"][];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[list[QualityRun]] */
        Envelope_list_QualityRun__: {
            /** Data */
            data: components["schemas"]["QualityRun"][];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[list[Source]] */
        Envelope_list_Source__: {
            /** Data */
            data: components["schemas"]["Source"][];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[list[Table]] */
        Envelope_list_Table__: {
            /** Data */
            data: components["schemas"]["Table"][];
            meta: components["schemas"]["Meta"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Database */
            database: string;
            /** Schema Version */
            schema_version: string | null;
        };
        /** LayerTable */
        LayerTable: {
            /** Schema Name */
            schema_name: string;
            /** Table Name */
            table_name: string;
            /** Row Count */
            row_count: number;
            /**
             * Profiled At
             * Format: date-time
             */
            profiled_at: string;
        };
        /** Meta */
        Meta: {
            /** As Of */
            as_of?: string | null;
            /** Row Count */
            row_count: number;
            /** Source */
            source: string;
        };
        /** QualityCheck */
        QualityCheck: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Check Name */
            check_name: string;
            /** Check Source */
            check_source: string;
            /** Severity */
            severity: string;
            /** Passed */
            passed: boolean;
            /** Observed Value */
            observed_value: string | null;
            /** Threshold */
            threshold: string | null;
            /** Message */
            message: string | null;
            /**
             * Ran At
             * Format: date-time
             */
            ran_at: string;
        };
        /** QualityRun */
        QualityRun: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Ran At
             * Format: date-time
             */
            ran_at: string;
            /** N Checks */
            n_checks: number;
            /** N Passed */
            n_passed: number;
            /** N Error Failed */
            n_error_failed: number;
            /** N Warning Failed */
            n_warning_failed: number;
        };
        /** Source */
        Source: {
            /** Source Name */
            source_name: string;
            /** Description */
            description: string | null;
            /** Url */
            url: string | null;
            /** License */
            license: string | null;
            /** Update Frequency */
            update_frequency: string | null;
            /** Owner */
            owner: string | null;
            /** Batch Count */
            batch_count: number;
            /** Total Rows */
            total_rows: number;
            /** Last Batch At */
            last_batch_at: string | null;
            /** Last Status */
            last_status: string | null;
        };
        /** Table */
        Table: {
            /** Schema Name */
            schema_name: string;
            /** Table Name */
            table_name: string;
            /** Kind */
            kind: string;
            /** Comment */
            comment: string | null;
            /** Column Count */
            column_count: number;
            /** Row Count */
            row_count: number | null;
            /** Profiled At */
            profiled_at: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    sources_meta_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_Source__"];
                };
            };
        };
    };
    batches_meta_batches_get: {
        parameters: {
            query?: {
                /** @description Lọc theo tên nguồn. */
                source?: string | null;
                status?: ("running" | "success" | "failed") | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_Batch__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quality_meta_quality_get: {
        parameters: {
            query?: {
                status?: "all" | "failed" | "passed";
                /** @description Mặc định: lần chạy mới nhất. */
                run_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_QualityCheck__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quality_runs_meta_quality_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_QualityRun__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    layers_meta_layers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_LayerTable__"];
                };
            };
        };
    };
    tables_catalog_tables_get: {
        parameters: {
            query?: {
                /** @description raw | staging | core | analytics | meta */
                schema?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_Table__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    columns_catalog_tables__name__columns_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_Column__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
